### ISSUE TITLE
Graph.Cycles gives incorrect output

### ISSUE THREAD

**Issue by ViktoriiaBaib** [qcscine/molassembler#13]
Hello!

I noticed that scine_molassembler.Cycles gives incorrect atomic positions when I iterate through cycles - it just repeats the same numbers.
![Screen Shot 2023-09-21 at 2 50 24 PM](https://github.com/qcscine/molassembler/assets/35492311/934d6b19-5a59-4e15-b20c-5de975e5c2a5)

When ligands are different, the issue persists with atomic positions being mixed from different cycles into one.

Could you look into it?

My expected output is:
```[[(0, 3), (0, 4), (1, 3), (1, 4)], [(0, 7), (0, 8), (5, 7), (5, 8)], [(0, 11), (0, 12), (9, 11), (9, 12)]]```
[bino3.xyz.zip](https://github.com/qcscine/molassembler/files/12693651/bino3.xyz.zip)

**Comment by jan-grimo** [comment]
This is a bug in the python bindings. The `Cycles` iterator returns references to a `vector` which gets updated in every iteration. It seems `pybind` doesn't deep-copy the lists it retrieves in every iteration, which leads to the last relevant cycle to be repeated across the list of edges. 

It'll be fixed in our GitLab instance for the next release, but in the meantime [this patch](https://github.com/qcscine/molassembler/files/12737442/cycles-patch.txt) should fix it for you. Can you confirm that this works for the other cases you have, too?

**Comment by weymutht** [comment]
The patch mentioned above is included in Molassembler 2.0.1, released today.
